apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /opt/cni/bin
      containerPath: /opt/cni/bin
- role: worker
  extraMounts:
    - hostPath: /opt/cni/bin
      containerPath: /opt/cni/bin
networking:
  disableDefaultCNI: true
  podSubnet: 10.24.0.0/16