apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ext-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth1",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "10.23.0.0/16",
      "rangeStart": "10.23.0.100",
      "rangeStop": "10.23.240",
      "routes": [
        { "dst": "0.0.0.0/0"}
        ],
      "gateway": "10.23.0.1"}
    }'